name: CI

on:
  push:
    branches: [ "counter/context" ]

jobs:
  validate_code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webpackcountercontext

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies Installing
        run: npm i

      - name: Format
        run: npm run format:check

      - name: Lint
        run: npm run lint:check

      - name: Test
        run: npm run test

  merge-branch:
    permissions: write-all
    needs: validate_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Merge counter/context -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          message: Merge commit from counter/context into main
          github_token: ${{ secrets.GITHUB_TOKEN }}

  push_to_registry:
    name: Push Docker image counter-context to Docker Hub
    runs-on: ubuntu-latest
  
    needs: validate_code
    env:
      IMAGE_NAME: olivka07/counter-context
      BASE_PATH: ./webpackcountercontext
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.BASE_PATH }}
          file: ${{ env.BASE_PATH }}/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME}}:latest
        
  call-deploy-workflow:
    needs: merge-branch
    uses: Olivka07/benchmarks-react-state-managers/.github/workflows/main.yml@main
    secrets:
      deploying_url: ${{ secrets.DEPLOYING_COUNTER_CONTEXT_URL }}