name: CI
on:
  push:
    branches: [ "fetching/redux" ]
jobs:
  validate_code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webpackfetchingredux
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies Installing
        run: npm i
      - name: Format
        run: npm run format:check
      - name: Lint
        run: npm run lint:check
      - name: Test
        run: npm run test
        
  merge-branch:
    permissions: write-all
    needs: validate_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge fetching/redux -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          message: Merge commit from fetching/redux into main
          github_token: ${{ secrets.GITHUB_TOKEN }}