name: CI
on:
  push:
    branches: [ "fetching/effector" ]
jobs:
  validate_code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webpackfetchingeffector
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies Installing
        run: npm i
      - name: Format
        run: npm run format:check
      - name: Lint
        run: npm run lint:check
      - name: Test
        run: npm run test
        
  merge-branch:
    permissions: write-all
    needs: validate_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge fetching/effector -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          message: Merge commit from fetching/effector into main
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  push_to_registry:
    name: Push Docker image fetching-effector to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    needs: validate_code
    env:
      IMAGE_NAME: olivka07/fetching-effector
      BASE_PATH: ./webpackfetchingeffector
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.BASE_PATH }}
          file: ${{ env.BASE_PATH }}/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME}}:latest

  call-deploy-workflow:
    needs: merge-branch
    uses: Olivka07/benchmarks-react-state-managers/.github/workflows/main.yml@main
    secrets:
      deploying_url: ${{ secrets.DEPLOYING_FETCHING_EFFECTOR_URL }}