name: CD
on:
  workflow_call:
    secrets:
      deploying_url:
        required: true
jobs:
  deploy-by-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: curl -X POST "${{ secrets.deploying_url }}"

