name: CD
on:
  push:
    branches: [ "main" ]
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get last commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"
          echo "::set-output name=last_commit_msg::$COMMIT_MESSAGE"
    
      - name: Check for merge commit
        id: is_merge_commit
        run: |
          if [[ "${{ steps.get_commit_message.outputs.last_commit_msg }}" == *"Merge commit from"* ]]; then
            echo "::set-output name=is_merge::true"
          else
            echo "::set-output name=is_merge::false"
          fi
    
      - name: Deploy counter/context if it is merged from counter/context
        if: ${{ steps.is_merge_commit.outputs.is_merge }} && "${{ steps.get_commit_message.outputs.last_commit_msg }}" == *"counter/context"*
        run: echo 'Привет фром каунтер контекст'