name: CD
on:
  workflow_call:
    inputs:
      merged_branch:
        required: true
        type: string
jobs:
  deploy-by-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
    
      - name: Deploy Project to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_COUNTER_CONTEXT_ID }}
        if: inputs.merged_branch == 'counter/context'
        run: vercel --token ${{ env.VERCEL_TOKEN }} --prod --confirm --scope ${{ env.VERCEL_ORG_ID }} --project ${{ env.VERCEL_PROJECT_ID }}