name: CD
on:
  workflow_call:
    inputs:
      merged_branch:
        required: true
        type: string
jobs:
  deploy-by-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Check Secret
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Secret empty"
          else
            echo "Secret is AVAILABLE"
          fi
    
      - name: Deploy Project to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_qLXRwBcllB4CyiwkBpzWiK6B
          VERCEL_PROJECT_ID: prj_42QgK2dE5URfelohuQj5UFolZVa1
        if: inputs.merged_branch == 'counter/context'
        run: vercel --prod --confirm --token ZJVrk0PGjvZPpsvxJfo1eUnz --scope team_qLXRwBcllB4CyiwkBpzWiK6B