name: CD
on:
  pull_request:
    types: [closed]
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка ветки
        run: echo "Ветка, затриггерившая PR: ${{ github.head_ref }}"
        
  trigger_on_counter_context:
    if: github.head_ref == 'counter/context'
    runs-on: ubuntu-latest
    steps:
      - name: Триггер на пул реквест из контекста
        run: echo "Ветка каунтер контекст: ${{ github.head_ref }}"