name: CD
on:
  workflow_call:
    inputs:
      merged_branch:
        required: true
        type: string
jobs:
  deploy-by-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Deploy counter/context if it is merged from counter/context
        if: inputs.merged_branch == 'counter/context'
        run: echo ${{ inputs.merged_branch }}